name:
channels:
- defaults
- conda-forge
dependencies:
- python>=3.9
- pip>=21.3.1
- conda>=4.11.0
- pip:
    - psutil>=5.8.0
    - numpy>=1.21.5
    - matplotlib>=3.1.3
    - joblib>=1.1.0
    - gym>=0.24.1
    - torch>=1.10.0
    - Pillow>=9.0.1
    - ipywidgets>=7.6.5
    - tensorflow-probability>=0.15.0

