from xpag.agents.rljax_agents.algorithm.ddpg import DDPG
from xpag.agents.rljax_agents.algorithm.dqn import DQN
from xpag.agents.rljax_agents.algorithm.fqf import FQF
from xpag.agents.rljax_agents.algorithm.iqn import IQN
from xpag.agents.rljax_agents.algorithm.ppo import PPO
from xpag.agents.rljax_agents.algorithm.qrdqn import QRDQN
from xpag.agents.rljax_agents.algorithm.sac import SAC
from xpag.agents.rljax_agents.algorithm.sac_ae import SAC_AE
from xpag.agents.rljax_agents.algorithm.sac_discor import SAC_DisCor
from xpag.agents.rljax_agents.algorithm.sac_discrete import SAC_Discrete
from xpag.agents.rljax_agents.algorithm.td3 import TD3
from xpag.agents.rljax_agents.algorithm.tqc import TQC
